
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome');
const sleep = (waitTimeInMs) => new Promise(resolve => setTimeout(resolve, waitTimeInMs));

async function virtuoso_cors() {

  console.log(" -- Set configuration --")
  let options = new chrome.Options();
  options.addArguments("--no-sandbox");
  options.addArguments("--headless");
  options.addArguments("--disable-dev-shm-usage");

  let configDriver = new Builder()
                        .setChromeOptions(options)
                        .forBrowser('chrome')

  let chrome_container = process.env.chrome_container

  if (chrome_container && 0 !== chrome_container.length) {
    let urlContainer = 'http://'+chrome_container+':4444/wd/hub'
    console.log(' -- using server : Container name  :'+urlContainer)
    configDriver.usingServer(urlContainer)
  } else {
    console.log(' -- None def : Container name  !! using a local chrome !! ')
  }

  let driver = await configDriver.build();

  console.log('-- start --');
  console.log("Virtuoso URL:"+process.env.virtuoso_site+"/conductor/");

  let vars = {}

  try {
      await driver.get(process.env.virtuoso_site+"/conductor/")
      await driver.manage().window().setRect(1920, 1054)
      await driver.findElement(By.id("t_login_usr")).sendKeys(process.env.login)
      await driver.findElement(By.id("t_login_pwd")).sendKeys(process.env.passwd)
      await driver.findElement(By.id("t_login_pwd")).sendKeys(Key.ENTER)
      await driver.findElement(By.linkText("Web Application Server")).click()
      await driver.findElement(By.linkText("Virtual Domains & Directories")).click()
      await driver.findElement(By.id("t1_toggle")).click()
      await driver.findElement(By.css(".listing_row_odd:nth-child(17) a:nth-child(1)")).click()
      await driver.findElement(By.id("t_cors")).click()
      await driver.findElement(By.id("t_cors")).clear()
      await driver.findElement(By.id("t_cors")).sendKeys("*")
      await driver.findElement(By.name("save")).click()
      await driver.quit();
  }  catch (e) {
    console.log(e)
  }
}

virtuoso_cors().then( x => console.log("Fin !"))
               .catch(error => console.error(error))
