version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.2

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BRANCH
          docker build -t inraep2m2/$CIRCLE_PROJECT_REPONAME:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push inraep2m2/$CIRCLE_PROJECT_REPONAME:$TAG
