version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - DOCKER_CONTEXT

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: ${DOCKER_USER}
          password: ${DOCKER_PASS}
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
             IMAGE=${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
             echo "build and push ${IMAGE}"
             docker build -t ${ORGANIZATION_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .
             echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
             docker tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} ${ORGANIZATION_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
             docker push ${ORGANIZATION_NAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
