version: 2.1
workflows:
  docker-publication-workflow:
    jobs:
      - build:
          context:
            - DOCKER_CONTEXT
      - latest:
          context:
            - DOCKER_CONTEXT
          requires:
            - build
          filters:
            tags:
              only: circleci-project-setup
            branches:
              ignore: /.*/
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
      IMAGE_LATEST: ${CIRCLE_PROJECT_REPONAME}:latest
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: ${DOCKER_USER}
          password: ${DOCKER_PASS}

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
             docker build -t ${ORGANIZATION_NAME}/${IMAGE_NAME} .
             echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
             docker push ${ORGANIZATION_NAME}/${IMAGE_NAME}
  latest:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker "Latest" tag
          command: |
             docker build -t ${ORGANIZATION_NAME}/${IMAGE_NAME} .
             echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
             docker push ${ORGANIZATION_NAME}/${IMAGE_NAME}
