version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BRANCH
          echo "$DOCKER_USER $DOCKER_PASS"
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker build -t inraep2m2/$CIRCLE_PROJECT_REPONAME:$TAG .
          docker push inraep2m2/$CIRCLE_PROJECT_REPONAME:$TAG
