version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - DOCKER_CONTEXT

jobs:
  build:
    machine: true
    steps:
      - checkout
      # build and push Docker image
      - run: |
          echo "build and push ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}"
          echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
          docker build -t inraep2m2/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .
          docker push inraep2m2/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
